### ISSUE TITLE
Proposal: Use official license (MIT / Apache 2.0)

### ISSUE THREAD

**Issue by beevelop** [ArtskydJ/hash-to-array#5]
Currently `hash-to-array` might lead to failed CI / CDs due to the configured license. Even though the current `master` points to the **VOL**, `license-checker` fails with the following exception:
```
 $ npx license-checker
 Package "hash-to-array@1.0.1" is licensed under "Custom: https://travis-ci.org/ArtskydJ/hash-to-array.svg" which is not permitted by the --onlyAllow flag. Exiting.
```

It can be easily solved by whitelisting the dependency, but I'd recommend using a well-known license like MIT / Apache 2.0 for "corporate compatibility". **VOL** sounds pretty promising from the conceptional point of view, but I never heard of it before 🙈 

Either way, I respect any choice of license and thank you for maintaining this lib 🙏

**Comment by ArtskydJ** [comment]
I'm fine with changing it to MIT.

**Comment by ArtskydJ** [comment]
1.0.2 is MIT

**Comment by beevelop** [comment]
Wow, that was quick 😍 Thank you in the name of the whole NeoSEALs team 🍻
